import { calendator } from "../MODULES/module.calendator/";
calendator.project = [
  "linkid",
  "title",
  "description",
  "est_startdate",
  "est_enddate",
  "est_hours",
  "actual_startdate",
  "actual_enddate",
  "actual_hours",
  "est_income",
  "actual_income",
  "features",
  "tasks",
  "timesheets",
  "punchcards",
  "documents",
  "bid_entered",
  "bid_won",
  "flags",
  "x_1",
  "x_2",
  "x_3",
  "x_4",
  "x_5",
  "x_6",
];
calendator.project.pkey = "linkid";
export { calendator };
